# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=256, verbose_name='\u8bb0\u5f55')),
                ('type', models.CharField(blank=True, choices=[('A', 'A'), ('CNAME', 'CNAME'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('NS', 'NS')], max_length=25, verbose_name='\u7c7b\u578b')),
                ('data', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9ed8\u8ba4')),
                ('data_tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7535\u4fe1')),
                ('data_net', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8054\u901a')),
                ('ttl', models.IntegerField(blank=True, default=10, null=True)),
                ('max_priority', models.IntegerField(blank=True, null=True)),
                ('refresh', models.IntegerField(blank=True, null=True)),
                ('retry', models.IntegerField(blank=True, null=True)),
                ('expire', models.IntegerField(blank=True, null=True)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('resp_contact', models.CharField(max_length=256)),
                ('primary_ns', models.CharField(max_length=256)),
                ('ctime', models.DateField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('active', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=250, unique=True, verbose_name='\u57df')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='\u63cf\u8ff0')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('active', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u57df',
                'verbose_name_plural': '\u57df',
            },
        ),
        migrations.AddField(
            model_name='records',
            name='zone',
            field=models.ForeignKey(db_column='zone', on_delete=django.db.models.deletion.CASCADE, to='mybind.Zones', to_field='zone', verbose_name='\u57df'),
        ),
    ]
