# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allownet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('num', models.CharField(max_length=256, verbose_name='\u5de5\u53f7')),
                ('qq', models.IntegerField(blank=True, null=True, verbose_name='QQ')),
                ('mac', models.CharField(max_length=25, verbose_name='MAC')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('ctime', models.DateField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u529e\u516c\u533a\u5165\u7f51\u4fe1\u606f',
                'verbose_name_plural': '\u529e\u516c\u533a\u5165\u7f51\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u90e8\u95e8')),
                ('desc', models.CharField(max_length=256, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('projectype', models.CharField(choices=[('test', '\u6d4b\u8bd5'), ('prod', '\u751f\u4ea7')], max_length=256, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('operate', models.CharField(choices=[('linux 6.5', 'linux 6.5'), ('linux 7.0', 'linux 7.0'), ('windows 2008', 'windows 2008'), ('kvm', 'kvm'), ('esxi', 'esxi')], default='linux 6.5', max_length=256, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu', models.CharField(choices=[('2', '2'), ('4', '4'), ('8', '8'), ('12', '12'), ('16', '16'), ('24', '24'), ('64z`', '64')], default=8, max_length=256)),
                ('memory', models.CharField(choices=[('8', '8'), ('16', '16'), ('32', '32'), ('64', '64'), ('128', '128'), ('more', 'more')], default=8, max_length=256, verbose_name='\u5185\u5b58(G)')),
                ('diskspace', models.CharField(choices=[('500', '500'), ('600', '600'), ('1000', '1000'), ('2000', '2000'), ('4000', '4000')], default=500, max_length=256, verbose_name='\u78c1\u76d8\u5bb9\u91cf(GB)')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Online')),
                ('zt', models.BooleanField(default=True, verbose_name='\u5ba1\u6838')),
                ('note', models.TextField(blank=True, help_text='\u6216\u586b\u5199\u5e94\u7528\u5b89\u88c5\u3001\u6570\u636e\u3001\u914d\u7f6e\u6587\u4ef6\u76ee\u5f55\u4ee5\u53ca\u6ce8\u610f\u4e8b\u9879\u7b49', verbose_name='\u5e94\u7528\u53ca\u7cfb\u7edf\u6982\u8ff0')),
                ('authorization', models.CharField(blank=True, max_length=256, verbose_name='\u8bbf\u95ee\u6743\u9650')),
                ('backup', models.CharField(choices=[('\u6574\u673a\u5907\u4efd', '\u6574\u673a\u5907\u4efd'), ('\u914d\u7f6e\u6587\u4ef6', '\u914d\u7f6e\u6587\u4ef6'), ('\u5e94\u7528\u6570\u636e', '\u5e94\u7528\u6570\u636e'), ('\u65e0\u9700\u5907\u4efd', '\u65e0\u9700\u5907\u4efd')], default='\u65e0\u9700\u5907\u4efd', max_length=256, verbose_name='\u5907\u4efd')),
            ],
            options={
                'ordering': ['ctime'],
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('projectype', models.CharField(choices=[('test', '\u6d4b\u8bd5'), ('prod', '\u751f\u4ea7')], max_length=256, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('operate', models.CharField(choices=[('linux 6.5', 'linux 6.5'), ('linux 7.0', 'linux 7.0'), ('windows 2008', 'windows 2008'), ('kvm', 'kvm'), ('esxi', 'esxi')], default='linux 6.5', max_length=256, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu', models.CharField(choices=[('2', '2'), ('4', '4'), ('8', '8'), ('16', '16')], default=4, max_length=256)),
                ('memory', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('12', '12'), ('more', 'more')], default=4, max_length=256, verbose_name='\u5185\u5b58(G)')),
                ('diskspace', models.CharField(choices=[('100', '100'), ('150', '150'), ('200', '200'), ('300', '300'), ('more', 'more')], default=200, max_length=256, verbose_name='\u78c1\u76d8\u5bb9\u91cf(GB)')),
                ('backup', models.CharField(choices=[('\u6574\u673a\u5907\u4efd', '\u6574\u673a\u5907\u4efd'), ('\u914d\u7f6e\u6587\u4ef6', '\u914d\u7f6e\u6587\u4ef6'), ('\u5e94\u7528\u6570\u636e', '\u5e94\u7528\u6570\u636e'), ('\u65e0\u9700\u5907\u4efd', '\u65e0\u9700\u5907\u4efd')], default='\u65e0\u9700\u5907\u4efd', max_length=256)),
                ('authorization', models.CharField(blank=True, max_length=256, verbose_name='\u8bbf\u95ee\u6743\u9650')),
                ('note', models.TextField(blank=True, help_text='\u6216\u586b\u5199\u5e94\u7528\u5b89\u88c5\u3001\u6570\u636e\u3001\u914d\u7f6e\u6587\u4ef6\u76ee\u5f55\u4ee5\u53ca\u6ce8\u610f\u4e8b\u9879\u7b49', verbose_name='\u5e94\u7528\u53ca\u7cfb\u7edf\u6982\u8ff0')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True)),
                ('zt', models.BooleanField(default=True, verbose_name='\u5ba1\u6838')),
                ('active', models.BooleanField(default=True, verbose_name='Online')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managEng.Devices', verbose_name='\u7269\u7406\u673a')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u673a',
                'verbose_name_plural': '\u865a\u62df\u673a',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP address')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managEng.Devices', verbose_name='\u4e3b\u673a')),
                ('hostname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managEng.Hosts', verbose_name='\u865a\u62df\u673a')),
            ],
            options={
                'verbose_name': 'IP \u5730\u5740',
                'verbose_name_plural': 'IP \u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Ipsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startip', models.GenericIPAddressField(unique=True)),
                ('endip', models.GenericIPAddressField(unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=40)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP \u6bb5',
                'verbose_name_plural': 'IP \u6bb5',
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offzone', models.CharField(choices=[('\u5965\u76db\u5927\u53a6', '\u5965\u76db\u5927\u53a6'), ('\u5927\u9646\u673a\u7535', '\u5927\u9646\u673a\u7535'), ('\u9f50\u6cb3', '\u9f50\u6cb3'), ('\u677f\u623f', '\u677f\u623f')], max_length=256, verbose_name='\u529e\u516c\u533a')),
                ('floor', models.CharField(max_length=25, verbose_name='\u697c\u5c42')),
                ('version', models.CharField(max_length=200, verbose_name='\u6253\u5370\u673a\u578b\u53f7')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('printype', models.CharField(choices=[('\u5f69\u8272\u6253\u5370', '\u5f69\u8272\u6253\u5370'), ('\u672c\u5730\u6253\u5370', '\u672c\u5730\u6253\u5370'), ('\u7f51\u7edc\u6253\u5370', '\u7f51\u7edc\u6253\u5370')], max_length=200, verbose_name='\u6253\u5370\u7c7b\u578b')),
                ('ctime', models.DateField(auto_now=True, verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managEng.Dept', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u6253\u5370\u673a',
                'verbose_name_plural': '\u6253\u5370\u673a',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('officer', models.CharField(blank=True, max_length=256, verbose_name='\u8d1f\u8d23\u4eba')),
                ('num', models.CharField(max_length=256, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('email', models.EmailField(help_text='\u8fd9\u662f\u4e00\u4e2a\u5fc5\u586b\u9879\uff0c\u4ee5\u4fbf\u5f53\u6dfb\u52a0\u65b0\u4e3b\u673a\u65f6\u901a\u77e5\u5230\u8d1f\u8d23\u4eba', max_length=254, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('desc', models.TextField(blank=True, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Wireless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('Terminal', models.CharField(choices=[('\u624b\u673a', '\u624b\u673a'), ('\u7b14\u8bb0\u672c', '\u7b14\u8bb0\u672c'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=25, verbose_name='\u7ec8\u7aef\u7c7b\u578b')),
                ('mac', models.CharField(max_length=25, unique=True, verbose_name='MAC')),
                ('Checked', models.BooleanField(default=True, verbose_name='\u90e8\u95e8\u9886\u5bfc\u5ba1\u6838')),
                ('fortime', models.DateField(blank=True, help_text='\u9ed8\u8ba4\u4e3a\u7a7a\u65f6\uff0c\u8868\u793a\u4e0d\u9650\u671f\u9650', null=True, verbose_name='\u4f7f\u7528\u65f6\u9650')),
                ('ctime', models.DateField(auto_now=True, verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('desc', models.CharField(max_length=256, verbose_name='\u7533\u8bf7\u539f\u56e0')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managEng.Dept', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u65e0\u7ebf\u8bbe\u5907',
                'verbose_name_plural': '\u65e0\u7ebf\u8bbe\u5907',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managEng.Projects', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='usergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='devices',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managEng.Projects', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='devices',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='allownet',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managEng.Dept', verbose_name='\u90e8\u95e8'),
        ),
    ]
